/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import tools.Util;
import view.JDlgRtc_VendedorPesquisar;

/**
 *
 * @author Jaque
 */
public class JDlgRtc_Vendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgRtc_Vendedor
     */
    public JDlgRtc_Vendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedores");
        setLocationRelativeTo(null);
        
        Util.habilitar(false, jTxtRtc_Codigo,jTxtRtc_Nome, jTxtRtc_Email, jTxtRtc_Endereco, jTxtRtc_Cidade, jFmtRtc_Cnpj, jFmtRtc_Telefone, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnRtc_Cancelar = new javax.swing.JButton();
        jTxtRtc_Cidade = new javax.swing.JTextField();
        jBtnRtc_Pesquisar = new javax.swing.JButton();
        jLblTelefone = new javax.swing.JLabel();
        jLblCodigo = new javax.swing.JLabel();
        jFmtRtc_Telefone = new javax.swing.JFormattedTextField();
        jTxtRtc_Codigo = new javax.swing.JTextField();
        jLblCnpj = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jFmtRtc_Cnpj = new javax.swing.JFormattedTextField();
        jTxtRtc_Nome = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLblEmail = new javax.swing.JLabel();
        jBtnRtc_Incluir = new javax.swing.JButton();
        jTxtRtc_Email = new javax.swing.JTextField();
        jBtnRtc_Alterar = new javax.swing.JButton();
        jLblEndereco = new javax.swing.JLabel();
        jBtnRtc_Excluir = new javax.swing.JButton();
        jTxtRtc_Endereco = new javax.swing.JTextField();
        jBtnRtc_Confirmar = new javax.swing.JButton();
        jLblCidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnRtc_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnRtc_Cancelar.setText("Cancelar");
        jBtnRtc_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_CancelarActionPerformed(evt);
            }
        });

        jBtnRtc_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnRtc_Pesquisar.setText("Pesquisar");
        jBtnRtc_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_PesquisarActionPerformed(evt);
            }
        });

        jLblTelefone.setText("Telefone");

        jLblCodigo.setText("Código");

        try {
            jFmtRtc_Telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTxtRtc_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRtc_CodigoActionPerformed(evt);
            }
        });

        jLblCnpj.setText("CNPJ");

        jLblNome.setText("Nome");

        try {
            jFmtRtc_Cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##. ###. ###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLblEmail.setText("E-mail");

        jBtnRtc_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnRtc_Incluir.setText("Incluir");
        jBtnRtc_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_IncluirActionPerformed(evt);
            }
        });

        jBtnRtc_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnRtc_Alterar.setText("Alterar");
        jBtnRtc_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_AlterarActionPerformed(evt);
            }
        });

        jLblEndereco.setText("Endereço");

        jBtnRtc_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnRtc_Excluir.setText("Excluir");
        jBtnRtc_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_ExcluirActionPerformed(evt);
            }
        });

        jBtnRtc_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnRtc_Confirmar.setText("Confirmar");
        jBtnRtc_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_ConfirmarActionPerformed(evt);
            }
        });

        jLblCidade.setText("Cidade");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBtnRtc_Incluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnRtc_Alterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnRtc_Excluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnRtc_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRtc_Cancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnRtc_Pesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblTelefone, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblEndereco, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblEmail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jFmtRtc_Telefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(jLblCidade, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtRtc_Cidade, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtRtc_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLblCnpj))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jTxtRtc_Nome)
                            .addComponent(jTxtRtc_Codigo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtRtc_Endereco)
                            .addComponent(jTxtRtc_Email, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblEndereco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCidade)
                    .addComponent(jLblCnpj))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtRtc_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtRtc_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFmtRtc_Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRtc_Incluir)
                    .addComponent(jBtnRtc_Alterar)
                    .addComponent(jBtnRtc_Excluir)
                    .addComponent(jBtnRtc_Cancelar)
                    .addComponent(jBtnRtc_Pesquisar)
                    .addComponent(jBtnRtc_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRtc_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_CancelarActionPerformed
        // TODO add your handling code here:
      Util.habilitar(true,jTxtRtc_Codigo,jTxtRtc_Nome, jTxtRtc_Email, jTxtRtc_Endereco, jTxtRtc_Cidade, jFmtRtc_Cnpj, jFmtRtc_Telefone, jBtnRtc_Confirmar, jBtnRtc_Cancelar );
      Util.habilitar(false, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar );
    }//GEN-LAST:event_jBtnRtc_CancelarActionPerformed

    private void jBtnRtc_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgRtc_VendedorPesquisar jDlgVendedorPesquisar = new JDlgRtc_VendedorPesquisar(null, true);
        jDlgVendedorPesquisar.setTelaPai(this);
        jDlgVendedorPesquisar.setVisible(true);
      
    }//GEN-LAST:event_jBtnRtc_PesquisarActionPerformed

    private void jTxtRtc_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRtc_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRtc_CodigoActionPerformed

    private void jBtnRtc_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_IncluirActionPerformed
        // TODO add your handling code here:
      Util.habilitar(true,jTxtRtc_Codigo,jTxtRtc_Nome, jTxtRtc_Email, jTxtRtc_Endereco, jTxtRtc_Cidade, jFmtRtc_Cnpj, jFmtRtc_Telefone, jBtnRtc_Confirmar, jBtnRtc_Cancelar );
      Util.habilitar(false, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar );
      Util.limpar(jTxtRtc_Codigo,jTxtRtc_Nome, jTxtRtc_Email, jTxtRtc_Endereco, jTxtRtc_Cidade, jFmtRtc_Cnpj, jFmtRtc_Telefone, jBtnRtc_Confirmar, jBtnRtc_Cancelar );
    }//GEN-LAST:event_jBtnRtc_IncluirActionPerformed

    private void jBtnRtc_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_AlterarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtRtc_Nome, jTxtRtc_Email, jTxtRtc_Endereco, jTxtRtc_Cidade, jFmtRtc_Cnpj, jFmtRtc_Telefone, jBtnRtc_Confirmar, jBtnRtc_Cancelar );
      Util.habilitar(false, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar );
    }//GEN-LAST:event_jBtnRtc_AlterarActionPerformed

    private void jBtnRtc_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_ExcluirActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jBtnRtc_ExcluirActionPerformed

    private void jBtnRtc_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_ConfirmarActionPerformed
        // TODO add your handling code here:
       Util.habilitar(false,jTxtRtc_Codigo,jTxtRtc_Nome, jTxtRtc_Email, jTxtRtc_Endereco, jTxtRtc_Cidade, jFmtRtc_Cnpj, jFmtRtc_Telefone, jBtnRtc_Confirmar, jBtnRtc_Cancelar );
      Util.habilitar(true, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar );
    }//GEN-LAST:event_jBtnRtc_ConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Vendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRtc_Vendedor dialog = new JDlgRtc_Vendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRtc_Alterar;
    private javax.swing.JButton jBtnRtc_Cancelar;
    private javax.swing.JButton jBtnRtc_Confirmar;
    private javax.swing.JButton jBtnRtc_Excluir;
    private javax.swing.JButton jBtnRtc_Incluir;
    private javax.swing.JButton jBtnRtc_Pesquisar;
    private javax.swing.JFormattedTextField jFmtRtc_Cnpj;
    private javax.swing.JFormattedTextField jFmtRtc_Telefone;
    private javax.swing.JLabel jLblCidade;
    private javax.swing.JLabel jLblCnpj;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblEmail;
    private javax.swing.JLabel jLblEndereco;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblTelefone;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtRtc_Cidade;
    private javax.swing.JTextField jTxtRtc_Codigo;
    private javax.swing.JTextField jTxtRtc_Email;
    private javax.swing.JTextField jTxtRtc_Endereco;
    private javax.swing.JTextField jTxtRtc_Nome;
    // End of variables declaration//GEN-END:variables
}
