/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.RtcUsuario;
import java.text.SimpleDateFormat;
import tools.Util;
import view.JDlgRtc_UsuariosPesquisar;

/**
 *
 * @author Jaque
 */
public class JDlgRtc_Usuarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlgRtc_Usuarios
     */
    public JDlgRtc_Usuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Usuarios");
        setLocationRelativeTo(null);
        
        Util.habilitar(false, jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Apelido, jFmtRtc_Cpf, jFmtRtc_DataNascimento,jPwdRtc_Senha, jChbRtc_Ativo, jCboRtc_Nivel, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
        
    }
    
     public void viewBean(RtcUsuario usuarios) { 
        jTxtRtc_Codigo.setText(String.valueOf(usuarios.getRtcIdusuarios()));
        jTxtRtc_Nome.setText(String.valueOf(usuarios.getRtcNome()));
        jTxtRtc_Apelido.setText(String.valueOf(usuarios.getRtcApelido()));
        jFmtRtc_Cpf.setText(String.valueOf(usuarios.getRtcCpf()));
        jFmtRtc_DataNascimento.setText(Util.dateToStr(usuarios.getRtcDataNascimento())); 
        jPwdRtc_Senha.setText(String.valueOf(usuarios.getRtcSenha()));
        jCboRtc_Nivel.setSelectedItem(usuarios.getRtcNivel());
        if (usuarios.getRtcAtivo().equals("S")) {
            jChbRtc_Ativo.setSelected(true);
        } else {
            jChbRtc_Ativo.setSelected(false);
        }
        
        // usuarioPesquisado = true;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnRtc_Alterar = new javax.swing.JButton();
        jTxtRtc_Apelido = new javax.swing.JTextField();
        jBtnRtc_Excluir = new javax.swing.JButton();
        jLblCpf = new javax.swing.JLabel();
        jBtnRtc_Confirmar = new javax.swing.JButton();
        jFmtRtc_Cpf = new javax.swing.JFormattedTextField();
        jBtnRtc_Cancelar = new javax.swing.JButton();
        jLblSenha = new javax.swing.JLabel();
        jBtnRtc_Pesquisar = new javax.swing.JButton();
        jPwdRtc_Senha = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLblDataNascimento = new javax.swing.JLabel();
        jChbRtc_Ativo = new javax.swing.JCheckBox();
        jLblCodigo = new javax.swing.JLabel();
        jFmtRtc_DataNascimento = new javax.swing.JFormattedTextField();
        jTxtRtc_Codigo = new javax.swing.JTextField();
        jLblNivel = new javax.swing.JLabel();
        jLblNome = new javax.swing.JLabel();
        jCboRtc_Nivel = new javax.swing.JComboBox<>();
        jTxtRtc_Nome = new javax.swing.JTextField();
        jBtnRtc_Incluir = new javax.swing.JButton();
        jLblApelido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnRtc_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnRtc_Alterar.setText("Alterar");
        jBtnRtc_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_AlterarActionPerformed(evt);
            }
        });

        jBtnRtc_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnRtc_Excluir.setText("Excluir");
        jBtnRtc_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_ExcluirActionPerformed(evt);
            }
        });

        jLblCpf.setText("CPF");

        jBtnRtc_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnRtc_Confirmar.setText("Confirmar");
        jBtnRtc_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_ConfirmarActionPerformed(evt);
            }
        });

        try {
            jFmtRtc_Cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jBtnRtc_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnRtc_Cancelar.setText("Cancelar");
        jBtnRtc_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_CancelarActionPerformed(evt);
            }
        });

        jLblSenha.setText("Senha");

        jBtnRtc_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnRtc_Pesquisar.setText("Pesquisar");
        jBtnRtc_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_PesquisarActionPerformed(evt);
            }
        });

        jPwdRtc_Senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPwdRtc_SenhaActionPerformed(evt);
            }
        });

        jLblDataNascimento.setText("Data de Nascimento");

        jChbRtc_Ativo.setText("Ativo");

        jLblCodigo.setText("Código");

        try {
            jFmtRtc_DataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jTxtRtc_Codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRtc_CodigoActionPerformed(evt);
            }
        });

        jLblNivel.setText("Nível");

        jLblNome.setText("Nome");

        jCboRtc_Nivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Administrador", "Usuário simples", "Convidado", "Outro" }));

        jBtnRtc_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnRtc_Incluir.setText("Incluir");
        jBtnRtc_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_IncluirActionPerformed(evt);
            }
        });

        jLblApelido.setText("Apelido");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jBtnRtc_Incluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRtc_Alterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRtc_Excluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRtc_Confirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRtc_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnRtc_Pesquisar))
                    .addComponent(jSeparator1)
                    .addComponent(jTxtRtc_Codigo, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtRtc_Nome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtRtc_Apelido, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFmtRtc_Cpf, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                            .addComponent(jPwdRtc_Senha))
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jChbRtc_Ativo)
                                .addGap(69, 69, 69))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblNivel)
                                    .addComponent(jCboRtc_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblDataNascimento)
                                    .addComponent(jFmtRtc_DataNascimento)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLblApelido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNome, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCpf, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblSenha, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblApelido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Apelido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblCpf)
                    .addComponent(jLblDataNascimento)
                    .addComponent(jLblNivel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtRtc_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtRtc_DataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboRtc_Nivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPwdRtc_Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnRtc_Incluir)
                            .addComponent(jBtnRtc_Excluir)
                            .addComponent(jBtnRtc_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnRtc_Cancelar)
                            .addComponent(jBtnRtc_Pesquisar)
                            .addComponent(jBtnRtc_Alterar)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jChbRtc_Ativo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRtc_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_AlterarActionPerformed
        // TODO add your handling code here:
       Util.habilitar(true, jTxtRtc_Nome, jTxtRtc_Apelido, jFmtRtc_Cpf, jFmtRtc_DataNascimento,jPwdRtc_Senha, jChbRtc_Ativo, jCboRtc_Nivel, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
       Util.habilitar(false, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar);   
    }//GEN-LAST:event_jBtnRtc_AlterarActionPerformed

    private void jBtnRtc_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_ExcluirActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jBtnRtc_ExcluirActionPerformed

    private void jBtnRtc_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_ConfirmarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(false,jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Apelido, jFmtRtc_Cpf, jFmtRtc_DataNascimento,jPwdRtc_Senha, jChbRtc_Ativo, jCboRtc_Nivel, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
        Util.habilitar(true, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar);
    }//GEN-LAST:event_jBtnRtc_ConfirmarActionPerformed

    private void jBtnRtc_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_CancelarActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true,jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Apelido, jFmtRtc_Cpf, jFmtRtc_DataNascimento,jPwdRtc_Senha, jChbRtc_Ativo, jCboRtc_Nivel, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
        Util.habilitar(false, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar);   
    }//GEN-LAST:event_jBtnRtc_CancelarActionPerformed

    private void jBtnRtc_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgRtc_UsuariosPesquisar jDlgUsuariosPesquisar = new JDlgRtc_UsuariosPesquisar(null, true);
        jDlgUsuariosPesquisar.setTelaPai(this);
        jDlgUsuariosPesquisar.setVisible(true);
        
    }//GEN-LAST:event_jBtnRtc_PesquisarActionPerformed

    private void jPwdRtc_SenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPwdRtc_SenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPwdRtc_SenhaActionPerformed

    private void jTxtRtc_CodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRtc_CodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRtc_CodigoActionPerformed

    private void jBtnRtc_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_IncluirActionPerformed
        // TODO add your handling code here:
       Util.habilitar(true,jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Apelido, jFmtRtc_Cpf, jFmtRtc_DataNascimento,jPwdRtc_Senha, jChbRtc_Ativo, jCboRtc_Nivel, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
       Util.habilitar(false, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar); 
       Util.limpar(jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Apelido, jFmtRtc_Cpf, jFmtRtc_DataNascimento,jPwdRtc_Senha, jChbRtc_Ativo, jCboRtc_Nivel, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
       
    }//GEN-LAST:event_jBtnRtc_IncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRtc_Usuarios dialog = new JDlgRtc_Usuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRtc_Alterar;
    private javax.swing.JButton jBtnRtc_Cancelar;
    private javax.swing.JButton jBtnRtc_Confirmar;
    private javax.swing.JButton jBtnRtc_Excluir;
    private javax.swing.JButton jBtnRtc_Incluir;
    private javax.swing.JButton jBtnRtc_Pesquisar;
    private javax.swing.JComboBox<String> jCboRtc_Nivel;
    private javax.swing.JCheckBox jChbRtc_Ativo;
    private javax.swing.JFormattedTextField jFmtRtc_Cpf;
    private javax.swing.JFormattedTextField jFmtRtc_DataNascimento;
    private javax.swing.JLabel jLblApelido;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblCpf;
    private javax.swing.JLabel jLblDataNascimento;
    private javax.swing.JLabel jLblNivel;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JPasswordField jPwdRtc_Senha;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtRtc_Apelido;
    private javax.swing.JTextField jTxtRtc_Codigo;
    private javax.swing.JTextField jTxtRtc_Nome;
    // End of variables declaration//GEN-END:variables
}
