/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import dao.Rtc_ClientesDAO;
import dao.Rtc_UsuariosDAO;
import java.util.List;
import tools.Util;
import view.JDlgRtc_Usuarios;

/**
 *
 * @author Marcos
 */
public class JDlgRtc_ConsultaUsuarios extends javax.swing.JDialog {

    /**
     * Creates new form JDlgUsuariosPesquisar
     */
 
    Rtc_ControllerConsultasUsuarios rtc_ControllerConsultasUsuarios;
    Rtc_UsuariosDAO rtc_UsuariosDAO;

    public JDlgRtc_ConsultaUsuarios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Consulta de Usuários");
        
        rtc_ControllerConsultasUsuarios = new Rtc_ControllerConsultasUsuarios();
        rtc_UsuariosDAO = new Rtc_UsuariosDAO();
        List lista = (List)rtc_UsuariosDAO.listAll();
        rtc_ControllerConsultasUsuarios.setList(lista);
        jTblRtc_Consulta.setModel(rtc_ControllerConsultasUsuarios);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRtc_Consulta = new javax.swing.JTable();
        jBtnRtc_Ok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTxtRtc_Nome = new javax.swing.JTextField();
        jTxtRtc_Ativo = new javax.swing.JTextField();
        jLblRtc_Sexo = new javax.swing.JLabel();
        jBtnRtc_Consulta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTblRtc_Consulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblRtc_Consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblRtc_ConsultaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblRtc_Consulta);

        jBtnRtc_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnRtc_Ok.setText("OK");
        jBtnRtc_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_OkActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome");

        jLblRtc_Sexo.setText("Ativo");

        jBtnRtc_Consulta.setText("Consultar");
        jBtnRtc_Consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_ConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnRtc_Ok))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTxtRtc_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblRtc_Sexo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTxtRtc_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnRtc_Consulta)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtRtc_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblRtc_Sexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtRtc_Ativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnRtc_Consulta))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRtc_Ok)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRtc_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_OkActionPerformed
      this.setVisible(false);        
    }//GEN-LAST:event_jBtnRtc_OkActionPerformed

    private void jTblRtc_ConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblRtc_ConsultaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            jBtnRtc_OkActionPerformed(null);
        }
    }//GEN-LAST:event_jTblRtc_ConsultaMouseClicked

    private void jBtnRtc_ConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_ConsultaActionPerformed
        // TODO add your handling code here:
        if (jTxtRtc_Nome.getText().isEmpty()== false && jTxtRtc_Ativo.getText().isEmpty()== false ) {
            List lista = (List)rtc_UsuariosDAO.listNomeAtivo(jTxtRtc_Nome.getText(), jTxtRtc_Ativo.getText());
            rtc_ControllerConsultasUsuarios.setList(lista); 
        }else if(jTxtRtc_Nome.getText().isEmpty()== false ){
            List lista = (List)rtc_UsuariosDAO.listNome(jTxtRtc_Nome.getText());
            rtc_ControllerConsultasUsuarios.setList(lista); 
        } else if(jTxtRtc_Ativo.getText().isEmpty()== false ){
            List lista = (List)rtc_UsuariosDAO.listAtivo(jTxtRtc_Ativo.getText());
            rtc_ControllerConsultasUsuarios.setList(lista); 
        } else {
            List lista = (List) rtc_UsuariosDAO.listAll();
            rtc_ControllerConsultasUsuarios.setList(lista);
            
        }
        
        //fazer ifs para cosulta. 4 casos, pesquisar nada, pesquisar só um ( nome ou valor), pesquisar os dois 
    }//GEN-LAST:event_jBtnRtc_ConsultaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_ConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_ConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_ConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_ConsultaUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRtc_ConsultaUsuarios dialog = new JDlgRtc_ConsultaUsuarios(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRtc_Consulta;
    private javax.swing.JButton jBtnRtc_Ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblRtc_Sexo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblRtc_Consulta;
    private javax.swing.JTextField jTxtRtc_Ativo;
    private javax.swing.JTextField jTxtRtc_Nome;
    // End of variables declaration//GEN-END:variables
}
