/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.RtcProduto;
import dao.Rtc_ProdutosDAO;
import java.util.List;
import tools.Util;

/**
 *
 * @author Jaque
 */
public class JDlgRtc_ProdutosPesquisar extends javax.swing.JDialog {

    private JDlgRtc_Produtos jDlgRtc_Produtos;
    Rtc_ControllerProdutos controllerProdutos;

    /**
     * Creates new form JDlgRtc_ProdutosPesquisar
     */
    public JDlgRtc_ProdutosPesquisar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Pesquisar Produtos");

        Rtc_ProdutosDAO produtosDAO = new Rtc_ProdutosDAO();
        List lista = (List) produtosDAO.listAll();
        controllerProdutos = new Rtc_ControllerProdutos();
        controllerProdutos.setList(lista);
        jTblRtc_ProdutosPesquisar.setModel(controllerProdutos);
    }

    public void setTelaPai(JDlgRtc_Produtos jDlgRtc_Produtos) {
        this.jDlgRtc_Produtos = jDlgRtc_Produtos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblRtc_ProdutosPesquisar = new javax.swing.JTable();
        jBtnRtc_Ok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTblRtc_ProdutosPesquisar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblRtc_ProdutosPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblRtc_ProdutosPesquisarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblRtc_ProdutosPesquisar);

        jBtnRtc_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnRtc_Ok.setText("OK");
        jBtnRtc_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_OkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnRtc_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnRtc_Ok)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRtc_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_OkActionPerformed
        // TODO add your handling code here:
         if(jTblRtc_ProdutosPesquisar.getSelectedRow() == -1){
            Util.mensagem("Nenhuma linha selecionada.");
        } else {
            RtcProduto produtos =  controllerProdutos.getBean( jTblRtc_ProdutosPesquisar.getSelectedRow() );
            jDlgRtc_Produtos.beanView(produtos);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jBtnRtc_OkActionPerformed

    private void jTblRtc_ProdutosPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblRtc_ProdutosPesquisarMouseClicked
        // TODO add your handling code here:
         if(evt.getClickCount() == 2){
            jBtnRtc_OkActionPerformed(null);
        }
    }//GEN-LAST:event_jTblRtc_ProdutosPesquisarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_ProdutosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_ProdutosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_ProdutosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_ProdutosPesquisar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRtc_ProdutosPesquisar dialog = new JDlgRtc_ProdutosPesquisar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRtc_Ok;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblRtc_ProdutosPesquisar;
    // End of variables declaration//GEN-END:variables
}
