/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import tools.Util;
import view.JDlgRtc_ProdutosPesquisar;

/**
 *
 * @author Jaque
 */
public class JDlgRtc_Produtos extends javax.swing.JDialog {

    /**
     * Creates new form JDlgRtc_Produtos
     */
    public JDlgRtc_Produtos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Produtos");
        setLocationRelativeTo(null);
        
        Util.habilitar(false, jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Marca, jTxtRtc_Descricao, jFmtRtc_Preco, jCboRtc_Cor, jCboRtc_TipoProduto, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnRtc_Confirmar = new javax.swing.JButton();
        jTxtRtc_Descricao = new javax.swing.JTextField();
        jBtnRtc_Cancelar = new javax.swing.JButton();
        jLblMarca = new javax.swing.JLabel();
        jBtnRtc_Pesquisar = new javax.swing.JButton();
        jTxtRtc_Marca = new javax.swing.JTextField();
        jLblCor = new javax.swing.JLabel();
        jLblPreco = new javax.swing.JLabel();
        jCboRtc_Cor = new javax.swing.JComboBox<>();
        jFmtRtc_Preco = new javax.swing.JFormattedTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLblTipoProduto = new javax.swing.JLabel();
        jLblCodigo = new javax.swing.JLabel();
        jCboRtc_TipoProduto = new javax.swing.JComboBox<>();
        jTxtRtc_Codigo = new javax.swing.JTextField();
        jBtnRtc_Incluir = new javax.swing.JButton();
        jLblNome = new javax.swing.JLabel();
        jBtnRtc_Alterar = new javax.swing.JButton();
        jTxtRtc_Nome = new javax.swing.JTextField();
        jBtnRtc_Excluir = new javax.swing.JButton();
        jLblDescricao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnRtc_Confirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        jBtnRtc_Confirmar.setText("Confirmar");
        jBtnRtc_Confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_ConfirmarActionPerformed(evt);
            }
        });

        jBtnRtc_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancelar.png"))); // NOI18N
        jBtnRtc_Cancelar.setText("Cancelar");
        jBtnRtc_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_CancelarActionPerformed(evt);
            }
        });

        jLblMarca.setText("Marca");

        jBtnRtc_Pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pesquisar.png"))); // NOI18N
        jBtnRtc_Pesquisar.setText("Pesquisar");
        jBtnRtc_Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_PesquisarActionPerformed(evt);
            }
        });

        jTxtRtc_Marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtRtc_MarcaActionPerformed(evt);
            }
        });

        jLblCor.setText("Cor");

        jLblPreco.setText("Preço (R$)");

        jCboRtc_Cor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Verde", "Vermelho", "Azul", "Preto", "Branco", "RGB" }));
        jCboRtc_Cor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboRtc_CorActionPerformed(evt);
            }
        });

        jFmtRtc_Preco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jFmtRtc_Preco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtRtc_PrecoActionPerformed(evt);
            }
        });

        jLblTipoProduto.setText("Tipo de Produto");

        jLblCodigo.setText("Código");

        jCboRtc_TipoProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Teclado  ", "Mouse  ", "Monitor  ", "Headset  ", "Webcam  ", "Caixa de som  ", "Microfone  ", "Suporte de monitor" }));

        jBtnRtc_Incluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/incluir.png"))); // NOI18N
        jBtnRtc_Incluir.setText("Incluir");
        jBtnRtc_Incluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_IncluirActionPerformed(evt);
            }
        });

        jLblNome.setText("Nome");

        jBtnRtc_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alterar.png"))); // NOI18N
        jBtnRtc_Alterar.setText("Alterar");
        jBtnRtc_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_AlterarActionPerformed(evt);
            }
        });

        jBtnRtc_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Excluir.png"))); // NOI18N
        jBtnRtc_Excluir.setText("Excluir");
        jBtnRtc_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRtc_ExcluirActionPerformed(evt);
            }
        });

        jLblDescricao.setText("Descrição");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLblPreco))
                                    .addComponent(jFmtRtc_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(112, 112, 112)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblCor)
                                    .addComponent(jCboRtc_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblTipoProduto)
                                    .addComponent(jCboRtc_TipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLblMarca))
                                .addComponent(jTxtRtc_Nome)
                                .addComponent(jTxtRtc_Marca)
                                .addComponent(jTxtRtc_Descricao)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnRtc_Incluir)
                                        .addGap(28, 28, 28)
                                        .addComponent(jBtnRtc_Alterar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnRtc_Excluir)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnRtc_Confirmar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnRtc_Cancelar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jBtnRtc_Pesquisar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLblDescricao)))
                                .addComponent(jTxtRtc_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLblNome)))
                        .addGap(0, 21, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLblCodigo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblCodigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLblMarca)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPreco)
                    .addComponent(jLblCor)
                    .addComponent(jLblTipoProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCboRtc_Cor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtRtc_Preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboRtc_TipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jLblDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtRtc_Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnRtc_Incluir)
                    .addComponent(jBtnRtc_Alterar)
                    .addComponent(jBtnRtc_Excluir)
                    .addComponent(jBtnRtc_Confirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnRtc_Cancelar)
                    .addComponent(jBtnRtc_Pesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnRtc_ConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_ConfirmarActionPerformed
        // TODO add your handling code here:
      Util.habilitar(false, jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Marca, jTxtRtc_Descricao, jFmtRtc_Preco, jCboRtc_Cor, jCboRtc_TipoProduto, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
      Util.habilitar(true, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar);
    }//GEN-LAST:event_jBtnRtc_ConfirmarActionPerformed

    private void jBtnRtc_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_CancelarActionPerformed
        // TODO add your handling code here:
      Util.habilitar(true, jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Marca, jTxtRtc_Descricao, jFmtRtc_Preco, jCboRtc_Cor, jCboRtc_TipoProduto, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
      Util.habilitar(false, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar);
    }//GEN-LAST:event_jBtnRtc_CancelarActionPerformed

    private void jBtnRtc_PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_PesquisarActionPerformed
        // TODO add your handling code here:
        JDlgRtc_ProdutosPesquisar jDlgProdutosPesquisar = new JDlgRtc_ProdutosPesquisar(null, true);
        jDlgProdutosPesquisar.setTelaPai(this);
        jDlgProdutosPesquisar.setVisible(true);
       
    }//GEN-LAST:event_jBtnRtc_PesquisarActionPerformed

    private void jTxtRtc_MarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtRtc_MarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtRtc_MarcaActionPerformed

    private void jCboRtc_CorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboRtc_CorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboRtc_CorActionPerformed

    private void jFmtRtc_PrecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtRtc_PrecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtRtc_PrecoActionPerformed

    private void jBtnRtc_IncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_IncluirActionPerformed
        // TODO add your handling code here:
        Util.habilitar(true, jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Marca, jTxtRtc_Descricao, jFmtRtc_Preco, jCboRtc_Cor, jCboRtc_TipoProduto, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
        Util.habilitar(false, jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar);
        Util.limpar(jTxtRtc_Codigo, jTxtRtc_Nome, jTxtRtc_Marca, jTxtRtc_Descricao, jFmtRtc_Preco, jCboRtc_Cor, jCboRtc_TipoProduto, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
    }//GEN-LAST:event_jBtnRtc_IncluirActionPerformed

    private void jBtnRtc_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_AlterarActionPerformed
        // TODO add your handling code here:
      Util.habilitar(true, jTxtRtc_Nome, jTxtRtc_Marca, jTxtRtc_Descricao, jFmtRtc_Preco, jCboRtc_Cor, jCboRtc_TipoProduto, jBtnRtc_Confirmar, jBtnRtc_Cancelar);
      Util.habilitar(false , jBtnRtc_Incluir, jBtnRtc_Alterar, jBtnRtc_Excluir, jBtnRtc_Pesquisar);
    }//GEN-LAST:event_jBtnRtc_AlterarActionPerformed

    private void jBtnRtc_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRtc_ExcluirActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jBtnRtc_ExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgRtc_Produtos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgRtc_Produtos dialog = new JDlgRtc_Produtos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnRtc_Alterar;
    private javax.swing.JButton jBtnRtc_Cancelar;
    private javax.swing.JButton jBtnRtc_Confirmar;
    private javax.swing.JButton jBtnRtc_Excluir;
    private javax.swing.JButton jBtnRtc_Incluir;
    private javax.swing.JButton jBtnRtc_Pesquisar;
    private javax.swing.JComboBox<String> jCboRtc_Cor;
    private javax.swing.JComboBox<String> jCboRtc_TipoProduto;
    private javax.swing.JFormattedTextField jFmtRtc_Preco;
    private javax.swing.JLabel jLblCodigo;
    private javax.swing.JLabel jLblCor;
    private javax.swing.JLabel jLblDescricao;
    private javax.swing.JLabel jLblMarca;
    private javax.swing.JLabel jLblNome;
    private javax.swing.JLabel jLblPreco;
    private javax.swing.JLabel jLblTipoProduto;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtRtc_Codigo;
    private javax.swing.JTextField jTxtRtc_Descricao;
    private javax.swing.JTextField jTxtRtc_Marca;
    private javax.swing.JTextField jTxtRtc_Nome;
    // End of variables declaration//GEN-END:variables
}
