/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Jaque
 */
public class JFrmRtc_Principal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmRtc_Principal
     */
    public JFrmRtc_Principal() {
       initComponents();
        setTitle("Sistema de Vendas de Periféricos");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuRtc_Cadastros = new javax.swing.JMenu();
        jMnuRtc_Clientes = new javax.swing.JMenuItem();
        JMnuRtc_Usuarios = new javax.swing.JMenuItem();
        jMnuRtc_Produtos = new javax.swing.JMenuItem();
        jMnuRtc_Vendedor = new javax.swing.JMenuItem();
        jMnuRtc_Sair = new javax.swing.JMenuItem();
        jMnuRtc_Movimentos = new javax.swing.JMenu();
        jMnuRtc_Vendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuRtc_Cadastros.setText("Cadastros");

        jMnuRtc_Clientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuRtc_Clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMnuRtc_Clientes.setText("Clientes");
        jMnuRtc_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuRtc_ClientesActionPerformed(evt);
            }
        });
        jMnuRtc_Cadastros.add(jMnuRtc_Clientes);

        JMnuRtc_Usuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        JMnuRtc_Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuário.png"))); // NOI18N
        JMnuRtc_Usuarios.setText("Usuários");
        JMnuRtc_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMnuRtc_UsuariosActionPerformed(evt);
            }
        });
        jMnuRtc_Cadastros.add(JMnuRtc_Usuarios);

        jMnuRtc_Produtos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuRtc_Produtos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMnuRtc_Produtos.setText("Produtos");
        jMnuRtc_Produtos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuRtc_ProdutosActionPerformed(evt);
            }
        });
        jMnuRtc_Cadastros.add(jMnuRtc_Produtos);

        jMnuRtc_Vendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuRtc_Vendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/vendedor.png"))); // NOI18N
        jMnuRtc_Vendedor.setText("Vendedor");
        jMnuRtc_Vendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuRtc_VendedorActionPerformed(evt);
            }
        });
        jMnuRtc_Cadastros.add(jMnuRtc_Vendedor);

        jMnuRtc_Sair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuRtc_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit.png"))); // NOI18N
        jMnuRtc_Sair.setText("Sair");
        jMnuRtc_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuRtc_SairActionPerformed(evt);
            }
        });
        jMnuRtc_Cadastros.add(jMnuRtc_Sair);

        jMenuBar1.add(jMnuRtc_Cadastros);

        jMnuRtc_Movimentos.setText("Movimentos");

        jMnuRtc_Vendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuRtc_Vendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/produto.png"))); // NOI18N
        jMnuRtc_Vendas.setText("Vendas");
        jMnuRtc_Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuRtc_VendasActionPerformed(evt);
            }
        });
        jMnuRtc_Movimentos.add(jMnuRtc_Vendas);

        jMenuBar1.add(jMnuRtc_Movimentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuRtc_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuRtc_ClientesActionPerformed
        // TODO add your handling code here:
        JDlgRtc_Clientes jDlgClientes = new JDlgRtc_Clientes(this, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnuRtc_ClientesActionPerformed

    private void jMnuRtc_VendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuRtc_VendedorActionPerformed
        // TODO add your handling code here:
        JDlgRtc_Vendedor jDlgVendedor = new JDlgRtc_Vendedor(this, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuRtc_VendedorActionPerformed

    private void jMnuRtc_VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuRtc_VendasActionPerformed
        // TODO add your handling code here:
       // JDlgRtc_Vendas jDlgVendas = new JDlgRtc_Vendas(this, true);
        //jDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMnuRtc_VendasActionPerformed

    private void JMnuRtc_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMnuRtc_UsuariosActionPerformed
        // TODO add your handling code here:
        JDlgRtc_Usuarios jDlgUsuarios = new JDlgRtc_Usuarios(this, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_JMnuRtc_UsuariosActionPerformed

    private void jMnuRtc_ProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuRtc_ProdutosActionPerformed
        // TODO add your handling code here:
        JDlgRtc_Produtos jDlgProdutos = new JDlgRtc_Produtos(this, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMnuRtc_ProdutosActionPerformed

    private void jMnuRtc_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuRtc_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuRtc_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmRtc_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmRtc_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmRtc_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmRtc_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmRtc_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMnuRtc_Usuarios;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMnuRtc_Cadastros;
    private javax.swing.JMenuItem jMnuRtc_Clientes;
    private javax.swing.JMenu jMnuRtc_Movimentos;
    private javax.swing.JMenuItem jMnuRtc_Produtos;
    private javax.swing.JMenuItem jMnuRtc_Sair;
    private javax.swing.JMenuItem jMnuRtc_Vendas;
    private javax.swing.JMenuItem jMnuRtc_Vendedor;
    // End of variables declaration//GEN-END:variables
}
