package bean;
// Generated 11/10/2025 16:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RtcCliente generated by hbm2java
 */
@Entity
@Table(name="rtc_cliente"
   
)
public class RtcCliente  implements java.io.Serializable {


     private int rtcIdcliente;
     private String rtcNome;
     private String rtcCpf;
     private String rtcEmail;
     private String rtcCelular;
     private String rtcEndereco;
     private String rtcBairro;
     private String rtcCidade;
     private String rtcEstado;
     private String rtcCep;
     private Date rtcDataNascimento;
     private String rtcSexo;
     private Date rtcDataCadastro;
     private int rtcTipoCliente;
     private String rtcAtivo;
    

    public RtcCliente() {
    }

	
    public RtcCliente(int rtcIdcliente) {
        this.rtcIdcliente = rtcIdcliente;
    }
    public RtcCliente(int rtcIdcliente, String rtcNome, String rtcCpf, String rtcEmail, String rtcCelular, String rtcEndereco, String rtcBairro, String rtcCidade, String rtcEstado, String rtcCep, Date rtcDataNascimento, String rtcSexo, Date rtcDataCadastro, int rtcTipoCliente, String rtcAtivo) {
       this.rtcIdcliente = rtcIdcliente;
       this.rtcNome = rtcNome;
       this.rtcCpf = rtcCpf;
       this.rtcEmail = rtcEmail;
       this.rtcCelular = rtcCelular;
       this.rtcEndereco = rtcEndereco;
       this.rtcBairro = rtcBairro;
       this.rtcCidade = rtcCidade;
       this.rtcEstado = rtcEstado;
       this.rtcCep = rtcCep;
       this.rtcDataNascimento = rtcDataNascimento;
       this.rtcSexo = rtcSexo;
       this.rtcDataCadastro = rtcDataCadastro;
       this.rtcTipoCliente = rtcTipoCliente;
       this.rtcAtivo = rtcAtivo;
      
    }
   
     @Id 

    
    @Column(name="rtc_idcliente", unique=true, nullable=false)
    public int getRtcIdcliente() {
        return this.rtcIdcliente;
    }
    
    public void setRtcIdcliente(int rtcIdcliente) {
        this.rtcIdcliente = rtcIdcliente;
    }

    
    @Column(name="rtc_nome", length=100)
    public String getRtcNome() {
        return this.rtcNome;
    }
    
    public void setRtcNome(String rtcNome) {
        this.rtcNome = rtcNome;
    }

    
    @Column(name="rtc_cpf", length=14)
    public String getRtcCpf() {
        return this.rtcCpf;
    }
    
    public void setRtcCpf(String rtcCpf) {
        this.rtcCpf = rtcCpf;
    }

    
    @Column(name="rtc_email", length=80)
    public String getRtcEmail() {
        return this.rtcEmail;
    }
    
    public void setRtcEmail(String rtcEmail) {
        this.rtcEmail = rtcEmail;
    }

    
    @Column(name="rtc_celular", length=15)
    public String getRtcCelular() {
        return this.rtcCelular;
    }
    
    public void setRtcCelular(String rtcCelular) {
        this.rtcCelular = rtcCelular;
    }

    
    @Column(name="rtc_endereco", length=100)
    public String getRtcEndereco() {
        return this.rtcEndereco;
    }
    
    public void setRtcEndereco(String rtcEndereco) {
        this.rtcEndereco = rtcEndereco;
    }

    
    @Column(name="rtc_bairro", length=50)
    public String getRtcBairro() {
        return this.rtcBairro;
    }
    
    public void setRtcBairro(String rtcBairro) {
        this.rtcBairro = rtcBairro;
    }

    
    @Column(name="rtc_cidade", length=50)
    public String getRtcCidade() {
        return this.rtcCidade;
    }
    
    public void setRtcCidade(String rtcCidade) {
        this.rtcCidade = rtcCidade;
    }

    
    @Column(name="rtc_estado", length=2)
    public String getRtcEstado() {
        return this.rtcEstado;
    }
    
    public void setRtcEstado(String rtcEstado) {
        this.rtcEstado = rtcEstado;
    }

    
    @Column(name="rtc_cep", length=9)
    public String getRtcCep() {
        return this.rtcCep;
    }
    
    public void setRtcCep(String rtcCep) {
        this.rtcCep = rtcCep;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rtc_dataNascimento", length=10)
    public Date getRtcDataNascimento() {
        return this.rtcDataNascimento;
    }
    
    public void setRtcDataNascimento(Date rtcDataNascimento) {
        this.rtcDataNascimento = rtcDataNascimento;
    }

    
    @Column(name="rtc_sexo", length=2)
    public String getRtcSexo() {
        return this.rtcSexo;
    }
    
    public void setRtcSexo(String rtcSexo) {
        this.rtcSexo = rtcSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rtc_dataCadastro", length=10)
    public Date getRtcDataCadastro() {
        return this.rtcDataCadastro;
    }
    
    public void setRtcDataCadastro(Date rtcDataCadastro) {
        this.rtcDataCadastro = rtcDataCadastro;
    }

    
    @Column(name="rtc_tipoCliente")
    public int getRtcTipoCliente() {
        return this.rtcTipoCliente;
    }
    
    public void setRtcTipoCliente(int rtcTipoCliente) {
        this.rtcTipoCliente = rtcTipoCliente;
    }

    
    @Column(name="rtc_ativo", length=1)
    public String getRtcAtivo() {
        return this.rtcAtivo;
    }
    
    public void setRtcAtivo(String rtcAtivo) {
        this.rtcAtivo = rtcAtivo;
    }

    @Override
    public String toString() {
    return this.getRtcNome(); // mostra o nome do cliente no combo box... 
    }  




}


