package bean;
// Generated 11/10/2025 16:43:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RtcProduto generated by hbm2java
 */
@Entity
@Table(name="rtc_produto"
    ,catalog="vendas"
)
public class RtcProduto  implements java.io.Serializable {


     private int rtcIdproduto;
     private String rtcNome;
     private String rtcDescricao;
     private String rtcMarca;
     private BigDecimal rtcPreco;
     private Integer rtcTipoProduto;
     private Integer rtcCor;
     private Set rtcVendasProdutoses = new HashSet(0);

    public RtcProduto() {
    }

	
    public RtcProduto(int rtcIdproduto, String rtcDescricao) {
        this.rtcIdproduto = rtcIdproduto;
        this.rtcDescricao = rtcDescricao;
    }
    public RtcProduto(int rtcIdproduto, String rtcNome, String rtcDescricao, String rtcMarca, BigDecimal rtcPreco, Integer rtcTipoProduto, Integer rtcCor, Set rtcVendasProdutoses) {
       this.rtcIdproduto = rtcIdproduto;
       this.rtcNome = rtcNome;
       this.rtcDescricao = rtcDescricao;
       this.rtcMarca = rtcMarca;
       this.rtcPreco = rtcPreco;
       this.rtcTipoProduto = rtcTipoProduto;
       this.rtcCor = rtcCor;
       this.rtcVendasProdutoses = rtcVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="rtc_idproduto", unique=true, nullable=false)
    public int getRtcIdproduto() {
        return this.rtcIdproduto;
    }
    
    public void setRtcIdproduto(int rtcIdproduto) {
        this.rtcIdproduto = rtcIdproduto;
    }

    
    @Column(name="rtc_nome", length=100)
    public String getRtcNome() {
        return this.rtcNome;
    }
    
    public void setRtcNome(String rtcNome) {
        this.rtcNome = rtcNome;
    }

    
    @Column(name="rtc_descricao", nullable=false)
    public String getRtcDescricao() {
        return this.rtcDescricao;
    }
    
    public void setRtcDescricao(String rtcDescricao) {
        this.rtcDescricao = rtcDescricao;
    }

    
    @Column(name="rtc_marca", length=50)
    public String getRtcMarca() {
        return this.rtcMarca;
    }
    
    public void setRtcMarca(String rtcMarca) {
        this.rtcMarca = rtcMarca;
    }

    
    @Column(name="rtc_preco", precision=10)
    public BigDecimal getRtcPreco() {
        return this.rtcPreco;
    }
    
    public void setRtcPreco(BigDecimal rtcPreco) {
        this.rtcPreco = rtcPreco;
    }

    
    @Column(name="rtc_tipoProduto")
    public Integer getRtcTipoProduto() {
        return this.rtcTipoProduto;
    }
    
    public void setRtcTipoProduto(Integer rtcTipoProduto) {
        this.rtcTipoProduto = rtcTipoProduto;
    }

    
    @Column(name="rtc_cor")
    public Integer getRtcCor() {
        return this.rtcCor;
    }
    
    public void setRtcCor(Integer rtcCor) {
        this.rtcCor = rtcCor;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rtcProduto")
    public Set getRtcVendasProdutoses() {
        return this.rtcVendasProdutoses;
    }
    
    public void setRtcVendasProdutoses(Set rtcVendasProdutoses) {
        this.rtcVendasProdutoses = rtcVendasProdutoses;
    }




}


