package bean;
// Generated 11/10/2025 16:43:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RtcProduto generated by hbm2java
 */
@Entity
@Table(name="rtc_produto"
    
)
public class RtcProduto  implements java.io.Serializable {


     private int rtcIdproduto;
     private String rtcNome;
     private String rtcDescricao;
     private String rtcMarca;
     private double rtcPreco;
     private int rtcTipoProduto;
     private int rtcCor;
    

    public RtcProduto() {
    }

	
    public RtcProduto(int rtcIdproduto, String rtcDescricao) {
        this.rtcIdproduto = rtcIdproduto;
        this.rtcDescricao = rtcDescricao;
    }
    public RtcProduto(int rtcIdproduto, String rtcNome, String rtcDescricao, String rtcMarca, double rtcPreco, int rtcTipoProduto, int rtcCor) {
       this.rtcIdproduto = rtcIdproduto;
       this.rtcNome = rtcNome;
       this.rtcDescricao = rtcDescricao;
       this.rtcMarca = rtcMarca;
       this.rtcPreco = rtcPreco;
       this.rtcTipoProduto = rtcTipoProduto;
       this.rtcCor = rtcCor;
       
    }
   
     @Id 

    
    @Column(name="rtc_idproduto", unique=true, nullable=false)
    public int getRtcIdproduto() {
        return this.rtcIdproduto;
    }
    
    public void setRtcIdproduto(int rtcIdproduto) {
        this.rtcIdproduto = rtcIdproduto;
    }

    
    @Column(name="rtc_nome", length=100)
    public String getRtcNome() {
        return this.rtcNome;
    }
    
    public void setRtcNome(String rtcNome) {
        this.rtcNome = rtcNome;
    }

    
    @Column(name="rtc_descricao", nullable=false)
    public String getRtcDescricao() {
        return this.rtcDescricao;
    }
    
    public void setRtcDescricao(String rtcDescricao) {
        this.rtcDescricao = rtcDescricao;
    }

    
    @Column(name="rtc_marca", length=50)
    public String getRtcMarca() {
        return this.rtcMarca;
    }
    
    public void setRtcMarca(String rtcMarca) {
        this.rtcMarca = rtcMarca;
    }

    
    @Column(name="rtc_preco", precision=10)
    public double getRtcPreco() {
        return this.rtcPreco;
    }
    
    public void setRtcPreco(double rtcPreco) {
        this.rtcPreco = rtcPreco;
    }

    
    @Column(name="rtc_tipoProduto")
    public int getRtcTipoProduto() {
        return this.rtcTipoProduto;
    }
    
    public void setRtcTipoProduto(int rtcTipoProduto) {
        this.rtcTipoProduto = rtcTipoProduto;
    }

    
    @Column(name="rtc_cor")
    public int getRtcCor() {
        return this.rtcCor;
    }
    
    public void setRtcCor(Integer rtcCor) {
        this.rtcCor = rtcCor;
    }


     @Override
    public String toString() {
        return this.rtcNome;
    }

    
 @Override
    public boolean equals( Object object){
        if(object instanceof RtcProduto) {
            RtcProduto rtcProduto = (RtcProduto)object;
            if(this.getRtcIdproduto()== rtcProduto.getRtcIdproduto()){
                return true;
            }
    }
        return false;
}



}


