package bean;
// Generated 11/10/2025 16:43:55 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RtcUsuario generated by hbm2java
 */
@Entity
@Table(name="rtc_usuario"
    ,catalog="db_rodrigo_cardozo"
)
public class RtcUsuario  implements java.io.Serializable {


     private int rtcIdusuarios;
     private String rtcNome;
     private String rtcApelido;
     private String rtcCpf;
     private Date rtcDataNascimento;
     private String rtcSenha;
     private int rtcNivel;
     private String rtcAtivo;

    public RtcUsuario() {
    }

	
    public RtcUsuario(int rtcIdusuarios) {
        this.rtcIdusuarios = rtcIdusuarios;
    }
    public RtcUsuario(int rtcIdusuarios, String rtcNome, String rtcApelido, String rtcCpf, Date rtcDataNascimento, String rtcSenha, int rtcNivel, String rtcAtivo) {
       this.rtcIdusuarios = rtcIdusuarios;
       this.rtcNome = rtcNome;
       this.rtcApelido = rtcApelido;
       this.rtcCpf = rtcCpf;
       this.rtcDataNascimento = rtcDataNascimento;
       this.rtcSenha = rtcSenha;
       this.rtcNivel = rtcNivel;
       this.rtcAtivo = rtcAtivo;
    }
   
     @Id 

    
    @Column(name="rtc_idusuarios", unique=true, nullable=false)
    public int getRtcIdusuarios() {
        return this.rtcIdusuarios;
    }
    
    public void setRtcIdusuarios(int rtcIdusuarios) {
        this.rtcIdusuarios = rtcIdusuarios;
    }

    
    @Column(name="rtc_nome", length=50)
    public String getRtcNome() {
        return this.rtcNome;
    }
    
    public void setRtcNome(String rtcNome) {
        this.rtcNome = rtcNome;
    }

    
    @Column(name="rtc_apelido", length=30)
    public String getRtcApelido() {
        return this.rtcApelido;
    }
    
    public void setRtcApelido(String rtcApelido) {
        this.rtcApelido = rtcApelido;
    }

    
    @Column(name="rtc_cpf", length=14)
    public String getRtcCpf() {
        return this.rtcCpf;
    }
    
    public void setRtcCpf(String rtcCpf) {
        this.rtcCpf = rtcCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rtc_dataNascimento", length=10)
    public Date getRtcDataNascimento() {
        return this.rtcDataNascimento;
    }
    
    public void setRtcDataNascimento(Date rtcDataNascimento) {
        this.rtcDataNascimento = rtcDataNascimento;
    }

    
    @Column(name="rtc_senha", length=20)
    public String getRtcSenha() {
        return this.rtcSenha;
    }
    
    public void setRtcSenha(String rtcSenha) {
        this.rtcSenha = rtcSenha;
    }

    
    @Column(name="rtc_nivel")
    public int getRtcNivel() {
        return this.rtcNivel;
    }
    
    public void setRtcNivel(int rtcNivel) {
        this.rtcNivel = rtcNivel;
    }

    
    @Column(name="rtc_ativo", length=1)
    public String getRtcAtivo() {
        return this.rtcAtivo;
    }
    
    public void setRtcAtivo(String rtcAtivo) {
        this.rtcAtivo = rtcAtivo;
    }




}


