package bean;
// Generated 11/10/2025 16:43:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RtcVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="rtc_vendas_produtos"
    ,catalog="vendas"
)
public class RtcVendasProdutos  implements java.io.Serializable {


     private int rtcIdvendasProdutos;
     private RtcProduto rtcProduto;
     private RtcVendas rtcVendas;
     private Integer rtcQuantidade;
     private BigDecimal rtcValorunitario;
     private BigDecimal rtcDesconto;

    public RtcVendasProdutos() {
    }

	
    public RtcVendasProdutos(int rtcIdvendasProdutos, BigDecimal rtcDesconto) {
        this.rtcIdvendasProdutos = rtcIdvendasProdutos;
        this.rtcDesconto = rtcDesconto;
    }
    public RtcVendasProdutos(int rtcIdvendasProdutos, RtcProduto rtcProduto, RtcVendas rtcVendas, Integer rtcQuantidade, BigDecimal rtcValorunitario, BigDecimal rtcDesconto) {
       this.rtcIdvendasProdutos = rtcIdvendasProdutos;
       this.rtcProduto = rtcProduto;
       this.rtcVendas = rtcVendas;
       this.rtcQuantidade = rtcQuantidade;
       this.rtcValorunitario = rtcValorunitario;
       this.rtcDesconto = rtcDesconto;
    }
   
     @Id 

    
    @Column(name="rtc_idvendas_produtos", unique=true, nullable=false)
    public int getRtcIdvendasProdutos() {
        return this.rtcIdvendasProdutos;
    }
    
    public void setRtcIdvendasProdutos(int rtcIdvendasProdutos) {
        this.rtcIdvendasProdutos = rtcIdvendasProdutos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rtc_idproduto")
    public RtcProduto getRtcProduto() {
        return this.rtcProduto;
    }
    
    public void setRtcProduto(RtcProduto rtcProduto) {
        this.rtcProduto = rtcProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rtc_idvenda")
    public RtcVendas getRtcVendas() {
        return this.rtcVendas;
    }
    
    public void setRtcVendas(RtcVendas rtcVendas) {
        this.rtcVendas = rtcVendas;
    }

    
    @Column(name="rtc_quantidade")
    public Integer getRtcQuantidade() {
        return this.rtcQuantidade;
    }
    
    public void setRtcQuantidade(Integer rtcQuantidade) {
        this.rtcQuantidade = rtcQuantidade;
    }

    
    @Column(name="rtc_valorunitario", precision=10)
    public BigDecimal getRtcValorunitario() {
        return this.rtcValorunitario;
    }
    
    public void setRtcValorunitario(BigDecimal rtcValorunitario) {
        this.rtcValorunitario = rtcValorunitario;
    }

    
    @Column(name="rtc_desconto", nullable=false, precision=10)
    public BigDecimal getRtcDesconto() {
        return this.rtcDesconto;
    }
    
    public void setRtcDesconto(BigDecimal rtcDesconto) {
        this.rtcDesconto = rtcDesconto;
    }




}


