package bean;
// Generated 11/10/2025 16:43:55 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RtcVendedor generated by hbm2java
 */
@Entity
@Table(name="rtc_vendedor"
    ,catalog="vendas"
)
public class RtcVendedor  implements java.io.Serializable {


     private int rtcIdvendedor;
     private String rtcNome;
     private String rtcCnpj;
     private String rtcEmail;
     private String rtcTelefone;
     private String rtcEndereco;
     private String rtcCidade;
     private Set rtcVendases = new HashSet(0);

    public RtcVendedor() {
    }

	
    public RtcVendedor(int rtcIdvendedor, String rtcEmail, String rtcTelefone) {
        this.rtcIdvendedor = rtcIdvendedor;
        this.rtcEmail = rtcEmail;
        this.rtcTelefone = rtcTelefone;
    }
    public RtcVendedor(int rtcIdvendedor, String rtcNome, String rtcCnpj, String rtcEmail, String rtcTelefone, String rtcEndereco, String rtcCidade, Set rtcVendases) {
       this.rtcIdvendedor = rtcIdvendedor;
       this.rtcNome = rtcNome;
       this.rtcCnpj = rtcCnpj;
       this.rtcEmail = rtcEmail;
       this.rtcTelefone = rtcTelefone;
       this.rtcEndereco = rtcEndereco;
       this.rtcCidade = rtcCidade;
       this.rtcVendases = rtcVendases;
    }
   
     @Id 

    
    @Column(name="rtc_idvendedor", unique=true, nullable=false)
    public int getRtcIdvendedor() {
        return this.rtcIdvendedor;
    }
    
    public void setRtcIdvendedor(int rtcIdvendedor) {
        this.rtcIdvendedor = rtcIdvendedor;
    }

    
    @Column(name="rtc_nome", length=100)
    public String getRtcNome() {
        return this.rtcNome;
    }
    
    public void setRtcNome(String rtcNome) {
        this.rtcNome = rtcNome;
    }

    
    @Column(name="rtc_cnpj", length=20)
    public String getRtcCnpj() {
        return this.rtcCnpj;
    }
    
    public void setRtcCnpj(String rtcCnpj) {
        this.rtcCnpj = rtcCnpj;
    }

    
    @Column(name="rtc_email", nullable=false, length=80)
    public String getRtcEmail() {
        return this.rtcEmail;
    }
    
    public void setRtcEmail(String rtcEmail) {
        this.rtcEmail = rtcEmail;
    }

    
    @Column(name="rtc_telefone", nullable=false, length=15)
    public String getRtcTelefone() {
        return this.rtcTelefone;
    }
    
    public void setRtcTelefone(String rtcTelefone) {
        this.rtcTelefone = rtcTelefone;
    }

    
    @Column(name="rtc_endereco", length=100)
    public String getRtcEndereco() {
        return this.rtcEndereco;
    }
    
    public void setRtcEndereco(String rtcEndereco) {
        this.rtcEndereco = rtcEndereco;
    }

    
    @Column(name="rtc_cidade", length=50)
    public String getRtcCidade() {
        return this.rtcCidade;
    }
    
    public void setRtcCidade(String rtcCidade) {
        this.rtcCidade = rtcCidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rtcVendedor")
    public Set getRtcVendases() {
        return this.rtcVendases;
    }
    
    public void setRtcVendases(Set rtcVendases) {
        this.rtcVendases = rtcVendases;
    }




}


