package bean;
// Generated 11/10/2025 16:43:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RtcVendas generated by hbm2java
 */
@Entity
@Table(name="rtc_vendas"
    ,catalog="vendas"
)
public class RtcVendas  implements java.io.Serializable {


     private int rtcIdvenda;
     private RtcCliente rtcCliente;
     private RtcVendedor rtcVendedor;
     private Date rtcDatavenda;
     private BigDecimal rtcTotal;
     private String rtcFormapagamento;
     private String rtcStatusvenda;
     private Set rtcVendasProdutoses = new HashSet(0);

    public RtcVendas() {
    }

	
    public RtcVendas(int rtcIdvenda) {
        this.rtcIdvenda = rtcIdvenda;
    }
    public RtcVendas(int rtcIdvenda, RtcCliente rtcCliente, RtcVendedor rtcVendedor, Date rtcDatavenda, BigDecimal rtcTotal, String rtcFormapagamento, String rtcStatusvenda, Set rtcVendasProdutoses) {
       this.rtcIdvenda = rtcIdvenda;
       this.rtcCliente = rtcCliente;
       this.rtcVendedor = rtcVendedor;
       this.rtcDatavenda = rtcDatavenda;
       this.rtcTotal = rtcTotal;
       this.rtcFormapagamento = rtcFormapagamento;
       this.rtcStatusvenda = rtcStatusvenda;
       this.rtcVendasProdutoses = rtcVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="rtc_idvenda", unique=true, nullable=false)
    public int getRtcIdvenda() {
        return this.rtcIdvenda;
    }
    
    public void setRtcIdvenda(int rtcIdvenda) {
        this.rtcIdvenda = rtcIdvenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rtc_idcliente")
    public RtcCliente getRtcCliente() {
        return this.rtcCliente;
    }
    
    public void setRtcCliente(RtcCliente rtcCliente) {
        this.rtcCliente = rtcCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rtc_idvendedor")
    public RtcVendedor getRtcVendedor() {
        return this.rtcVendedor;
    }
    
    public void setRtcVendedor(RtcVendedor rtcVendedor) {
        this.rtcVendedor = rtcVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="rtc_datavenda", length=10)
    public Date getRtcDatavenda() {
        return this.rtcDatavenda;
    }
    
    public void setRtcDatavenda(Date rtcDatavenda) {
        this.rtcDatavenda = rtcDatavenda;
    }

    
    @Column(name="rtc_total", precision=10)
    public BigDecimal getRtcTotal() {
        return this.rtcTotal;
    }
    
    public void setRtcTotal(BigDecimal rtcTotal) {
        this.rtcTotal = rtcTotal;
    }

    
    @Column(name="rtc_formapagamento", length=20)
    public String getRtcFormapagamento() {
        return this.rtcFormapagamento;
    }
    
    public void setRtcFormapagamento(String rtcFormapagamento) {
        this.rtcFormapagamento = rtcFormapagamento;
    }

    
    @Column(name="rtc_statusvenda", length=20)
    public String getRtcStatusvenda() {
        return this.rtcStatusvenda;
    }
    
    public void setRtcStatusvenda(String rtcStatusvenda) {
        this.rtcStatusvenda = rtcStatusvenda;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="rtcVendas")
    public Set getRtcVendasProdutoses() {
        return this.rtcVendasProdutoses;
    }
    
    public void setRtcVendasProdutoses(Set rtcVendasProdutoses) {
        this.rtcVendasProdutoses = rtcVendasProdutoses;
    }




}


