package bean;
// Generated 11/10/2025 16:43:55 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RtcVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="rtc_vendas_produtos"
    
)
public class RtcVendasProdutos  implements java.io.Serializable {


     private int rtcIdvendasProdutos;
     private RtcProduto rtcProduto;
     private RtcVendas rtcVendas;
     private int rtcQuantidade;
     private double rtcValorunitario;
     private double rtcDesconto;

    public RtcVendasProdutos() {
    }

	
    public RtcVendasProdutos(int rtcIdvendasProdutos, double rtcDesconto) {
        this.rtcIdvendasProdutos = rtcIdvendasProdutos;
        this.rtcDesconto = rtcDesconto;
    }
    public RtcVendasProdutos(int rtcIdvendasProdutos, RtcProduto rtcProduto, RtcVendas rtcVendas, int rtcQuantidade, double rtcValorunitario, double rtcDesconto) {
       this.rtcIdvendasProdutos = rtcIdvendasProdutos;
       this.rtcProduto = rtcProduto;
       this.rtcVendas = rtcVendas;
       this.rtcQuantidade = rtcQuantidade;
       this.rtcValorunitario = rtcValorunitario;
       this.rtcDesconto = rtcDesconto;
    }
   
     @Id 

    
    @Column(name="rtc_idvendas_produtos", unique=true, nullable=false)
    public int getRtcIdvendasProdutos() {
        return this.rtcIdvendasProdutos;
    }
    
    public void setRtcIdvendasProdutos(int rtcIdvendasProdutos) {
        this.rtcIdvendasProdutos = rtcIdvendasProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="rtc_idproduto")
    public RtcProduto getRtcProduto() {
        return this.rtcProduto;
    }
    
    public void setRtcProduto(RtcProduto rtcProduto) {
        this.rtcProduto = rtcProduto;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="rtc_idvenda")
    public RtcVendas getRtcVendas() {
        return this.rtcVendas;
    }
    
    public void setRtcVendas(RtcVendas rtcVendas) {
        this.rtcVendas = rtcVendas;
    }

    
    @Column(name="rtc_quantidade")
    public int getRtcQuantidade() {
        return this.rtcQuantidade;
    }
    
    public void setRtcQuantidade(int rtcQuantidade) {
        this.rtcQuantidade = rtcQuantidade;
    }

    
    @Column(name="rtc_valorunitario", precision=10)
    public double getRtcValorunitario() {
        return this.rtcValorunitario;
    }
    
    public void setRtcValorunitario(double rtcValorunitario) {
        this.rtcValorunitario = rtcValorunitario;
    }

    
    @Column(name="rtc_desconto", nullable=false, precision=10)
    public double getRtcDesconto() {
        return this.rtcDesconto;
    }
    
    public void setRtcDesconto(double rtcDesconto) {
        this.rtcDesconto = rtcDesconto;
    }




}


